# Generated by Django 6.0.5 on 2026-07-23 11:18

import adm_user.models
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('product_code', models.CharField(blank=True, help_text='e.g. SBB-001. Optional on the form, but unique if set.', max_length=50, null=True, unique=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional sale price; must be less than base_price.', max_digits=10, null=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Fallback stock count, used only if this product has no color variants below.')),
                ('saree_length', models.CharField(blank=True, help_text='e.g. 5.5 Meter', max_length=50)),
                ('blouse_included', models.BooleanField(default=True)),
                ('blouse_type', models.CharField(blank=True, max_length=100)),
                ('blouse_size', models.CharField(blank=True, max_length=50)),
                ('weaving_style', models.CharField(blank=True, max_length=100)),
                ('border_style', models.CharField(blank=True, max_length=150)),
                ('care_instructions', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Unpublish without deleting (keeps order history intact).')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(adm_user.models.SlugMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(help_text='Cloudflare R2 object URL.')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text="Leave blank to use the product's base_price.", max_digits=10, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=70, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(adm_user.models.SlugMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='fabric',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='print',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Prints'},
        ),
        migrations.AlterConstraint(
            model_name='category',
            name='unique_category_name_ci',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_category_name_ci', violation_error_message='This category already exists.'),
        ),
        migrations.AlterConstraint(
            model_name='color',
            name='unique_color_name_ci',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_color_name_ci', violation_error_message='This color already exists.'),
        ),
        migrations.AlterConstraint(
            model_name='fabric',
            name='unique_fabric_name_ci',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_fabric_name_ci', violation_error_message='This fabric already exists.'),
        ),
        migrations.AlterConstraint(
            model_name='print',
            name='unique_print_name_ci',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_print_name_ci', violation_error_message='This print already exists.'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='adm_user.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='adm_user.fabric'),
        ),
        migrations.AddField(
            model_name='product',
            name='print_type',
            field=models.ForeignKey(blank=True, help_text="Leave blank for prints like 'NO' / plain sarees.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='adm_user.print', verbose_name='print'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='adm_user.product'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_variants', to='adm_user.color'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='adm_user.product'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Leave blank for default/no-color-selected images.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='adm_user.productvariant'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_tag_name_ci', violation_error_message='This tag already exists.'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='adm_user.tag'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'color'), name='unique_color_per_product'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'fabric', 'print_type', 'is_active'], name='adm_user_pr_categor_18ba97_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', '-created_at'], name='adm_user_pr_is_acti_9ca906_idx'),
        ),
    ]
