# Generated by Django 6.0.6 on 2026-07-31 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('small_title', models.CharField(blank=True, max_length=100)),
                ('main_heading', models.CharField(blank=True, max_length=200)),
                ('highlight_quote', models.TextField(blank=True, help_text='Gold-highlighted quote; may contain non-English script.')),
                ('main_paragraph', models.TextField(blank=True, help_text='Main body text; may contain non-English script.')),
                ('ending_signoff', models.CharField(blank=True, max_length=200)),
                ('about_image', models.ImageField(upload_to='website/about/')),
                ('floating_top_text', models.CharField(blank=True, max_length=100)),
                ('floating_bottom_text', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(blank=True, max_length=150)),
                ('brand_description', models.TextField(blank=True)),
                ('store_address', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('instagram_link', models.URLField(blank=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeaderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(upload_to='website/branding/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeroSlideImageOnly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('desktop_image', models.ImageField(upload_to='website/hero/slide2/desktop/')),
                ('mobile_image', models.ImageField(upload_to='website/hero/slide2/mobile/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeroSlideMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tagline', models.CharField(blank=True, max_length=100)),
                ('title_line_1', models.CharField(blank=True, max_length=200)),
                ('title_line_2', models.CharField(blank=True, max_length=200)),
                ('title_line_3', models.CharField(blank=True, help_text='Rendered in gold on the frontend.', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('button_1_text', models.CharField(blank=True, max_length=50)),
                ('button_2_text', models.CharField(blank=True, max_length=50)),
                ('desktop_image', models.ImageField(upload_to='website/hero/slide1/desktop/')),
                ('mobile_image', models.ImageField(upload_to='website/hero/slide1/mobile/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeroSlideOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('small_top_text', models.CharField(blank=True, max_length=100)),
                ('big_highlight_text', models.CharField(blank=True, max_length=150)),
                ('subtext', models.CharField(blank=True, max_length=200)),
                ('button_text', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfferBarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='SweetMemoriesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_label', models.CharField(blank=True, max_length=100)),
                ('main_heading', models.TextField(blank=True, help_text="Multi-line heading, e.g. 'Woven Into / Your Beautiful Moments'.")),
                ('background_theme', models.CharField(choices=[('dark_maroon', 'Dark Maroon'), ('light_gold', 'Light Gold')], default='dark_maroon', max_length=20)),
                ('paragraph_text', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SweetMemoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='website/memories/')),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
