# Generated by Django 6.0.7 on 2026-08-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_user', '0002_aboutussection_footersettings_headersettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoriesOfferSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('desktop_image', models.ImageField(blank=True, upload_to='website/memories_offer/desktop/')),
                ('mobile_image', models.ImageField(blank=True, upload_to='website/memories_offer/mobile/')),
                ('title', models.CharField(blank=True, help_text="e.g. 'New Arrivals'", max_length=150)),
                ('subtitle', models.CharField(blank=True, help_text="e.g. 'Festive Paithani Collection'", max_length=200)),
                ('button_text', models.CharField(blank=True, default='Shop Now', max_length=50)),
                ('button_link', models.CharField(blank=True, default='#', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
