# Generated by Django 6.0.7 on 2026-08-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_user', '0003_memoriesofferslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoriesofferslide',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='website/memories_offer/frame1/'),
        ),
        migrations.AddField(
            model_name='memoriesofferslide',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='website/memories_offer/frame2/'),
        ),
    ]
