# Generated by Django 6.0.7 on 2026-08-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_user', '0004_memoriesofferslide_image_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoriesSlide3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('desktop_image', models.ImageField(blank=True, upload_to='website/memories_slide3/desktop/')),
                ('mobile_image', models.ImageField(blank=True, upload_to='website/memories_slide3/mobile/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='memoriesofferslide',
            name='button_link',
        ),
        migrations.RemoveField(
            model_name='memoriesofferslide',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='memoriesofferslide',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='memoriesofferslide',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='memoriesofferslide',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='memoriesofferslide',
            name='title',
        ),
        migrations.AlterField(
            model_name='memoriesofferslide',
            name='desktop_image',
            field=models.ImageField(blank=True, upload_to='website/memories_slide2/desktop/'),
        ),
        migrations.AlterField(
            model_name='memoriesofferslide',
            name='mobile_image',
            field=models.ImageField(blank=True, upload_to='website/memories_slide2/mobile/'),
        ),
    ]
