# Generated by Django 6.0.7 on 2026-08-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_user', '0005_memoriesslide3_remove_memoriesofferslide_button_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslideoffer',
            name='desktop_image',
            field=models.ImageField(blank=True, upload_to='website/hero/offer/desktop/'),
        ),
        migrations.AddField(
            model_name='heroslideoffer',
            name='mobile_image',
            field=models.ImageField(blank=True, upload_to='website/hero/offer/mobile/'),
        ),
    ]
