# Generated by Django 6.0.7 on 2026-08-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_user', '0006_heroslideoffer_desktop_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureCategoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('badge_text', models.CharField(blank=True, max_length=100)),
                ('origin_craft', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='website/signature/')),
                ('whatsapp_link', models.CharField(blank=True, max_length=500)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
