# Generated by Django 6.0.7 on 2026-08-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_user', '0007_signaturecategoryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoriesofferslide',
            name='frame1_image',
            field=models.ImageField(blank=True, upload_to='website/memories_slide1/frame1/'),
        ),
        migrations.AddField(
            model_name='memoriesofferslide',
            name='frame2_image',
            field=models.ImageField(blank=True, upload_to='website/memories_slide1/frame2/'),
        ),
        migrations.AddField(
            model_name='memoriesofferslide',
            name='frame3_image',
            field=models.ImageField(blank=True, upload_to='website/memories_slide1/frame3/'),
        ),
    ]
