# Generated by Django 6.0.7 on 2026-08-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_user', '0008_memoriesofferslide_frame1_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoriesofferslide',
            name='frame1_badge',
            field=models.CharField(blank=True, default='SPECIAL DEAL · UP TO 50% OFF', max_length=100),
        ),
        migrations.AddField(
            model_name='memoriesofferslide',
            name='frame1_ribbon',
            field=models.CharField(blank=True, default='50% OFF', max_length=50),
        ),
        migrations.AddField(
            model_name='memoriesofferslide',
            name='frame1_title',
            field=models.CharField(blank=True, default='Timeless Tradition Collection', max_length=255),
        ),
        migrations.AddField(
            model_name='memoriesofferslide',
            name='frame1_wa_link',
            field=models.CharField(blank=True, default='https://wa.me/919372471363?text=Hi%20Sanskruti%20By%20Bani,%20I%20want%20to%20know%20about%20Up%20To%2050%25%20Off%20Special%20Offer', max_length=500),
        ),
        migrations.AddField(
            model_name='memoriesofferslide',
            name='frame2_badge',
            field=models.CharField(blank=True, default='✦ WELCOME OFFER · 10% OFF ✦', max_length=100),
        ),
        migrations.AddField(
            model_name='memoriesofferslide',
            name='frame2_ribbon',
            field=models.CharField(blank=True, default='10% OFF', max_length=50),
        ),
        migrations.AddField(
            model_name='memoriesofferslide',
            name='frame2_title',
            field=models.CharField(blank=True, default='10% Off 1st Order (Code: WELCOME10)', max_length=255),
        ),
        migrations.AddField(
            model_name='memoriesofferslide',
            name='frame2_wa_link',
            field=models.CharField(blank=True, default='https://wa.me/919372471363?text=Hi%20Sanskruti%20By%20Bani,%20I%20want%20to%20avail%2010%25%20Off%20Welcome%20Offer%20with%20code%20WELCOME10', max_length=500),
        ),
        migrations.AddField(
            model_name='memoriesofferslide',
            name='frame3_badge',
            field=models.CharField(blank=True, default='RAKHI FESTIVE · UP TO 65% OFF', max_length=100),
        ),
        migrations.AddField(
            model_name='memoriesofferslide',
            name='frame3_ribbon',
            field=models.CharField(blank=True, default='65% OFF', max_length=50),
        ),
        migrations.AddField(
            model_name='memoriesofferslide',
            name='frame3_title',
            field=models.CharField(blank=True, default='Happy Rakhi Festive Special', max_length=255),
        ),
        migrations.AddField(
            model_name='memoriesofferslide',
            name='frame3_wa_link',
            field=models.CharField(blank=True, default='https://wa.me/919372471363?text=Hi%20Sanskruti%20By%20Bani,%20I%20want%20to%20know%20about%20Up%20To%2065%25%20Off%20Rakhi%20Offer', max_length=500),
        ),
    ]
