# Generated by Django 6.0.7 on 2026-08-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_user', '0009_memoriesofferslide_frame1_badge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslideimageonly',
            name='desktop_image',
            field=models.ImageField(blank=True, upload_to='website/hero/slide2/desktop/'),
        ),
        migrations.AlterField(
            model_name='heroslideimageonly',
            name='mobile_image',
            field=models.ImageField(blank=True, upload_to='website/hero/slide2/mobile/'),
        ),
        migrations.AlterField(
            model_name='heroslidemain',
            name='desktop_image',
            field=models.ImageField(blank=True, upload_to='website/hero/slide1/desktop/'),
        ),
        migrations.AlterField(
            model_name='heroslidemain',
            name='mobile_image',
            field=models.ImageField(blank=True, upload_to='website/hero/slide1/mobile/'),
        ),
    ]
