# Generated by Django 6.0.6 on 2026-08-18 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_user', '0011_signaturecategoryitem_slug_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='adm_user.signaturecategoryitem'),
        ),
        migrations.AlterField(
            model_name='signaturecategoryitem',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
