# Generated by Django 6.0.6 on 2026-08-18 05:58

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_user', '0013_alter_product_category'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='signaturecategoryitem',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_signature_category_name_ci', violation_error_message='This category already exists.'),
        ),
    ]
