# Generated by Django 6.0.5 on 2026-08-21 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm_user', '0014_signaturecategoryitem_unique_signature_category_name_ci'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroslideoffer',
            name='big_highlight_text',
        ),
        migrations.RemoveField(
            model_name='heroslideoffer',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='heroslideoffer',
            name='small_top_text',
        ),
        migrations.RemoveField(
            model_name='heroslideoffer',
            name='subtext',
        ),
    ]
