# Generated by Django 6.0.5 on 2026-08-21 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm_user', '0015_remove_heroslideoffer_big_highlight_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sweetmemoriessection',
            name='background_theme',
        ),
    ]
