# Generated by Django 6.0.6 on 2026-08-21 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm_user', '0016_remove_sweetmemoriessection_background_theme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['created_at']},
        ),
    ]
