# Generated by Django 6.0.6 on 2026-08-30 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm_user', '0018_alter_productvariant_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signaturecategoryitem',
            name='whatsapp_link',
        ),
    ]
