# Generated by Django 6.0.6 on 2026-09-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_user', '0019_remove_signaturecategoryitem_whatsapp_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='stock_quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Total stock quantity available for this product.'),
        ),
    ]
